# Generated by Django 5.0 on 2024-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DOING', 'DOING'), ('DONE', 'DONE')], default='PENDING', max_length=10),
        ),
    ]
