# Generated by Django 5.0 on 2024-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
