# Generated by Django 5.0 on 2024-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DOING', 'doing'), ('DONE', 'done')], default='PENDING', max_length=10),
        ),
    ]
